//THIS CLASS WOULD SERVE MORE OF A PURPOSE IF WE IMPLEMENTED MORE PLAYSTYLES OF BLACKJACK, 
//SINCE WE RAN OUT OF TIME, EXTRA FUNCTIONALITY WAS ABANDONED AND ONLY THE BASE FORM OF BLACKJACK REMAINED.
//THEREFORE IN THIS RELEASE, THE CLASS SOLELY ACTS AS A PLAYER WITH THE NAME "Dealer".
public class Dealer extends Player {
	
    /** Dealer constructor */
	public Dealer() {
		super("Dealer");
	}
}