import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

public class GameUI extends javax.swing.JFrame {

    private Game game;
    private int turn;
    
    public final Color WOOD = new Color(81,25,12);
    public final Color DARKWOOD = new Color(48,16,7);
    public final Color FELT = new Color(31,80,61);
    public final Color GOLD = new Color(201,146,56);
    
    public GameUI(Game game) {
        initComponents();
        decoComponents();
        
        this.game = game;
        game.firstDeal();
        this.turn = 0;
        
        refreshUI();
    }
    
    public void refreshUI() {
        this.setTitle(game.getPlayer(turn).getName() + "'s Turn");
        
        lblDealerHand.setText(labelCards(game.getDealer()));
        lblDealerScore.setText("Valued: " + game.getDealer().getHand().handValue());
        
        lblPlayer.setText(game.getPlayer(turn).getName() + "'s Hand");
        lblPlayerHand.setText(labelCards(game.getPlayer(turn)));
        lblPlayerScore.setText("Valued: " + game.getPlayer(turn).getHand().handValue());
    }
    
    public String labelCards(Player p) {
        String[] pCards = p.getHand().toUnicodeString();
        String out = "";
        for (int i = 0; i < pCards.length; i++) {
            out += pCards[i];
        }
        return out;
    }
    
    /** a compilation of statements related to decorating the window to have a "Blackjack table"-like appearance */
    private void decoComponents() {
        setLocationRelativeTo(null);
        pnlActions.setBackground(WOOD);
        pnlBoard.setBackground(FELT);
        pnlBoard.setBorder(javax.swing.BorderFactory.createLineBorder(WOOD, 10));
        btnHit.setBackground(GOLD);
        btnStand.setBackground(GOLD); 
        lblDealer.setForeground(GOLD);
        lblPlayer.setForeground(GOLD);
        lblDealerHand.setFont(new Font("", 0, 100));
        lblPlayerHand.setFont(new Font("", 0, 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlActions = new javax.swing.JPanel();
        btnHit = new javax.swing.JButton();
        btnStand = new javax.swing.JButton();
        pnlBoard = new javax.swing.JPanel();
        lblDealer = new javax.swing.JLabel();
        lblDealerHand = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        lblPlayerHand = new javax.swing.JLabel();
        lblDealerScore = new javax.swing.JLabel();
        lblPlayerScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        pnlActions.setBackground(new java.awt.Color(81, 25, 12));
        pnlActions.setPreferredSize(new java.awt.Dimension(800, 80));

        btnHit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnHit.setText("HIT");
        btnHit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitActionPerformed(evt);
            }
        });

        btnStand.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnStand.setText("STAND");
        btnStand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlActionsLayout = new javax.swing.GroupLayout(pnlActions);
        pnlActions.setLayout(pnlActionsLayout);
        pnlActionsLayout.setHorizontalGroup(
            pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionsLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnHit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btnStand, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        pnlActionsLayout.setVerticalGroup(
            pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionsLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStand, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnlBoard.setBackground(new java.awt.Color(0, 51, 0));
        pnlBoard.setPreferredSize(new java.awt.Dimension(800, 500));

        lblDealer.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        lblDealer.setForeground(new java.awt.Color(255, 255, 255));
        lblDealer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDealer.setText("Dealer's Hand");

        lblDealerHand.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        lblDealerHand.setForeground(new java.awt.Color(255, 255, 255));
        lblDealerHand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDealerHand.setText("??");

        lblPlayer.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        lblPlayer.setForeground(new java.awt.Color(255, 255, 255));
        lblPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer.setText("Player's Hand");

        lblPlayerHand.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        lblPlayerHand.setForeground(new java.awt.Color(255, 255, 255));
        lblPlayerHand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerHand.setText("??");

        lblDealerScore.setForeground(new java.awt.Color(255, 255, 255));
        lblDealerScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDealerScore.setText("Valued:");

        lblPlayerScore.setBackground(new java.awt.Color(255, 255, 255));
        lblPlayerScore.setForeground(new java.awt.Color(255, 255, 255));
        lblPlayerScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerScore.setText("Valued: ");

        javax.swing.GroupLayout pnlBoardLayout = new javax.swing.GroupLayout(pnlBoard);
        pnlBoard.setLayout(pnlBoardLayout);
        pnlBoardLayout.setHorizontalGroup(
            pnlBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDealerHand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDealer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPlayerHand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBoardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDealerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBoardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPlayerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBoardLayout.setVerticalGroup(
            pnlBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBoardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblDealer, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblDealerHand, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDealerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblPlayerHand, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPlayerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitActionPerformed
        Player tempPlayer = game.getPlayer(turn);
        Hand tempHand = tempPlayer.getHand();
        game.getDeck().dealCard(tempHand);
        
        
        if (tempPlayer.checkBust()) {
            refreshUI();
            JOptionPane.showMessageDialog(pnlBoard, tempPlayer.getName().toUpperCase() + " BUSTED!!");
            turn++;
        }
        refreshUI();
    }//GEN-LAST:event_btnHitActionPerformed

    private void btnStandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStandActionPerformed
        turn = (turn + 1)%game.PLAYER_COUNT;
        refreshUI();
    }//GEN-LAST:event_btnStandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GameUI().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHit;
    private javax.swing.JButton btnStand;
    private javax.swing.JLabel lblDealer;
    private javax.swing.JLabel lblDealerHand;
    private javax.swing.JLabel lblDealerScore;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblPlayerHand;
    private javax.swing.JLabel lblPlayerScore;
    private javax.swing.JPanel pnlActions;
    private javax.swing.JPanel pnlBoard;
    // End of variables declaration//GEN-END:variables
}
